### ISSUE TITLE
Some Armors don't render as intended

### ISSUE THREAD

**Issue by Kuggle01** [NyakoFox/VanitySlots#1]
Certain armor, such as the armor from bewitchment, doens't render correctly or just don't render at all. I think it's proably any armor that uses custome models
![2022-03-29_12 46 20](https://user-images.githubusercontent.com/77563171/160664248-49da1860-90eb-4b77-b5d4-e49dbdc7e7de.png)

**Comment by Footage2-Amply-Pounce** [comment]
[Immersive Armors](https://www.curseforge.com/minecraft/mc-mods/immersive-armors) also fail to render properly when equipped in a vanity slot; don't change appearance when another armor is equipped in a vanity slot, when wearing armor from IA.

**Comment by NyakoFox** [comment]
This seems related to #6, but I'll keep this open for now.

**Comment by NyakoFox** [comment]
This should be fixed now!
