### ISSUE TITLE
VanitySlots instant crash upon load.

### ISSUE THREAD

**Issue by bsodcat** [NyakoFox/VanitySlots#11]
At first it was a critical injection failure and now the second log shows more than one error NoClassDefFound and ClassNotFoundExeption.
I disabled all other mods to isolate in order to find conflicts and it seems to be a code issue that I'm not sure how to resolve.
https://paste.ee/p/PTJjt

**Comment by NyakoFox** [comment]
You need cloth config enabled as well.
