### ISSUE TITLE
Allow disabling the "Equipable in" text

### ISSUE THREAD

**Issue by Dekamir** [NyakoFox/VanitySlots#12]
On modded Minecraft, tooltips get kinda cluttered and I'd like to lessen that a bit.

Also allowing shortening them like "Chest Vanity" would be nice.

![2023-05-27_01 52 49](https://github.com/NyakoFox/VanitySlots/assets/28929300/2b1de4c4-b873-4970-baf2-48daa94f57f1)

**Comment by NyakoFox** [comment]
This is something that'll have to be done on the Trinkets side, I've opened an issue there for now

**Comment by NyakoFox** [comment]
The tooltip has been disabled completely, as I didn't like it there in the first place lol
