### ISSUE TITLE
Familiar set doesn't render properly

### ISSUE THREAD

**Issue by Yuri-Matsuki** [NyakoFox/VanitySlots#21]
![2024-07-29_21 55 32](https://github.com/user-attachments/assets/3ff7e51c-4b1c-44dd-81f5-d524ff37eef4)
![2024-07-29_21 55 30](https://github.com/user-attachments/assets/3f0972e6-b130-4ae8-b705-35a9aac6e1f8)

**Comment by Yuri-Matsuki** [comment]
Tested on 1.21

**Comment by NyakoFox** [comment]
Fixed in latest release, whoops
