### ISSUE TITLE
Familiar set can't be crafted

### ISSUE THREAD

**Issue by Yuri-Matsuki** [NyakoFox/VanitySlots#22]
![imagen_2024-08-10_195903520](https://github.com/user-attachments/assets/232bf437-907f-479e-8bb0-b20d080f9a3b)

**Comment by tester214243** [comment]
this can easily be fixed with a datpack [Familiar-set-fix.zip](https://github.com/user-attachments/files/16692088/Familiar-set-fix.zip)
