### ISSUE TITLE
Incompatibility with CITResewn

### ISSUE THREAD

**Issue by Alkiasan** [NyakoFox/VanitySlots#4]
As stated in https://github.com/SHsuperCM/CITResewn/issues/17 , CITResewn is incompatible with VanitySlots and other cosmetic armor mods, would it be at all possible for you to use its API to add support for CIT in vanity slots?

**Comment by NyakoFox** [comment]
I'll look into it once a 1.19.3 version is published.

**Comment by NyakoFox** [comment]
According to a curseforge comment, it seems to be fixed in the latest version.
