### ISSUE TITLE
Carved Pumpkins cannot be placed in Vanity Slot.

### ISSUE THREAD

**Issue by notabirb1** [NyakoFox/VanitySlots#5]
## Problem
Carved Pumpkins, while mostly useless in the regular game, can be a fun feature when combined with a custom resource pack to change the model (via CIT) to create custom hats. However, these cannot be equipped in the vanity slot, meaning you can't wear armor while still having the hat / pumpkin.
## Solution
Add Carved Pumpkins to the list of items that can be equipped in the Vanity Slot.

**Comment by NyakoFox** [comment]
fixed in 4294bda79d848b8198926228d34cd77d32471cfd, 1.2.3 will be released soon
