### ISSUE TITLE
Blacklist Curse of binding enchantment

### ISSUE THREAD

**Issue by Rav115** [NyakoFox/VanitySlots#8]
Like we have config for blacklisting items but how can we blacklist items with enchantment like Curse of binding
![Screenshot_20230112_030539](https://user-images.githubusercontent.com/39887530/211951421-0f755295-898e-49b5-8cd3-ad1c69291f4d.png)

**Comment by ToxicShourin** [comment]
Cannot even remove the item in creative mode like you can the vanilla armor slots. You have to use the "shift  click the red X"  clear to get rid of the binding items. For this you need a server op/owner to be online for if you pick up so your basically screwed if you play on a Hardcore world / server or a server that runs the "Dark RPG" mod pack where the mod pack is designed in a way where you cannot drop items upon death.

**Comment by NyakoFox** [comment]
Added a config option to disallow them (on by default), and try something like `/trinkets set head vanity 0 air` if you've already put something in the slot
